apiVersion: v1
kind: Service

metadata:
  name: secure-demo-app
  namespace: apps

spec:
  selector:
    app: secure-demo-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

  type: ClusterIP
